name: release-please npm-workspace lerna update

on:
  push:
    branches:
      - release-please--branches--main--components--release-please-demo-workspace

jobs:
  increase-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'npm-workspace/package-lock.json'

      - working-directory: npm-workspace
        run: npm ci

      - id: version
        working-directory: npm-workspace
        run: |
          version=$(jq '.version' -r  package.json)
          echo "version=$version" >> $GITHUB_OUTPUT

      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - working-directory: npm-workspace
        run: |
          npx lerna version $VERSION --yes --no-push --message="chore(main): Update versions with lerna"
        env:
          VERSION: ${{ steps.version.outputs.version }}

      - run: |
          git push origin release-please--branches--main--components--release-please-demo-workspace
