name: release-please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    outputs:
      release-please: ${{ toJSON(steps.release-please.outputs) }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          token: ${{ secrets.RELEASE_PLEASE_PAT }}

      - run: echo "$OUTPUT"
        env:
          OUTPUT: ${{ toJSON(steps.release-please.outputs) }}

  release-npm-workspace:
    needs:
      - release-please
    if: ${{ fromJSON(needs.release-please.outputs.release-please).npm-workspace--release_created == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'npm-workspace/package-lock.json'

      - working-directory: npm-workspace
        run: npm ci

      - working-directory: npm-workspace
        run: npx lerna publish from-git --tag-version-prefix="release-please-demo-workspace-v"